-- MySQL Script generated by MySQL Workbench
-- Вт 26 янв 2021 15:42:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop_cosmetics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop_cosmetics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop_cosmetics` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `shop_cosmetics` ;

-- -----------------------------------------------------
-- Table `shop_cosmetics`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(145) NOT NULL COMMENT 'имя',
  `lastname` VARCHAR(145) NOT NULL COMMENT 'фамилия',
  `email` VARCHAR(245) NOT NULL COMMENT 'электронная почта',
  `phone` BIGINT(12) NOT NULL COMMENT 'телефон',
  `password_hash` CHAR(65) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_cosmetics`.`type_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`type_media` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_cosmetics`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`media` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_media_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `url` VARCHAR(245) NULL DEFAULT NULL,
  `blob` BLOB NULL DEFAULT NULL,
  `size` BIGINT NOT NULL DEFAULT 0,
  `metadata` JSON NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_media_type_media1_idx` (`type_media_id` ASC) VISIBLE,
  CONSTRAINT `fk_media_type_media1`
    FOREIGN KEY (`type_media_id`)
    REFERENCES `shop_cosmetics`.`type_media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_cosmetics`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`profiles` (
  `users_id` INT UNSIGNED NOT NULL,
  `gender` ENUM('m', 'f') NOT NULL,
  `birthday` DATE NOT NULL,
  `adress` VARCHAR(245) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `media_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`users_id`),
  INDEX `fk_profiles_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_profiles_media1_idx` (`media_id` ASC) VISIBLE,
  CONSTRAINT `fk_profiles_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `shop_cosmetics`.`media` (`id`),
  CONSTRAINT `fk_profiles_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `shop_cosmetics`.`users` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_cosmetics`.`catalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`catalog` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_cosmetics`.`countru`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`countru` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `countru` VARCHAR(45) NOT NULL COMMENT 'страна-производитель',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`countru` ASC, `id` ASC) VISIBLE,
  UNIQUE INDEX `countru_UNIQUE` (`countru` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_cosmetics`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`section` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_cosmetics`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`brand` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `brand_UNIQUE` (`brand` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_cosmetics`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `catalog_id` INT UNSIGNED NOT NULL,
  `countru_id` INT UNSIGNED NOT NULL,
  `section_id` INT UNSIGNED NOT NULL,
  `brand_id` INT UNSIGNED NOT NULL,
  `media_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT 'наименование товара',
  `description` TEXT NOT NULL COMMENT 'подробное описание товара',
  `decode` BIGINT NOT NULL COMMENT 'штрих код',
  `price` DECIMAL(8,2) NOT NULL COMMENT 'цена',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_product_catalog1_idx` (`catalog_id` ASC) VISIBLE,
  INDEX `fk_product_countru1_idx` (`countru_id` ASC) VISIBLE,
  INDEX `fk_product_section1_idx` (`section_id` ASC) VISIBLE,
  INDEX `fk_product_brand1_idx` (`brand_id` ASC) VISIBLE,
  INDEX `fk_product_media1_idx` (`media_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_catalog1`
    FOREIGN KEY (`catalog_id`)
    REFERENCES `shop_cosmetics`.`catalog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_countru1`
    FOREIGN KEY (`countru_id`)
    REFERENCES `shop_cosmetics`.`countru` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_section1`
    FOREIGN KEY (`section_id`)
    REFERENCES `shop_cosmetics`.`section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `shop_cosmetics`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `shop_cosmetics`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_cosmetics`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_order_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `shop_cosmetics`.`users` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_cosmetics`.`discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`discounts` (
  `profiles_users_id` INT UNSIGNED NOT NULL,
  `discount` FLOAT NULL DEFAULT NULL,
  `started_at` DATE NULL DEFAULT NULL,
  `finished_at` DATE NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`profiles_users_id`),
  INDEX `fk_discounts_profiles1_idx` (`profiles_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_discounts_profiles1`
    FOREIGN KEY (`profiles_users_id`)
    REFERENCES `shop_cosmetics`.`profiles` (`users_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_cosmetics`.`rewiews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`rewiews` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rewiews` TEXT NULL DEFAULT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `profiles_users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rewiews_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_rewiews_profiles1_idx` (`profiles_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_rewiews_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shop_cosmetics`.`product` (`id`),
  CONSTRAINT `fk_rewiews_profiles1`
    FOREIGN KEY (`profiles_users_id`)
    REFERENCES `shop_cosmetics`.`profiles` (`users_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_cosmetics`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`likes` (
  `users_id` INT UNSIGNED NOT NULL,
  `rewiews_id` INT UNSIGNED NULL DEFAULT NULL,
  `product_id` INT UNSIGNED NULL DEFAULT NULL,
  INDEX `fk_likes_rewiews1_idx` (`rewiews_id` ASC) VISIBLE,
  INDEX `fk_likes_product1_idx` (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `index1` (`users_id` ASC, `rewiews_id` ASC) VISIBLE,
  UNIQUE INDEX `index2` (`users_id` ASC, `product_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shop_cosmetics`.`product` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_likes_rewiews1`
    FOREIGN KEY (`rewiews_id`)
    REFERENCES `shop_cosmetics`.`rewiews` (`id`),
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `shop_cosmetics`.`users` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_cosmetics`.`order_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop_cosmetics`.`order_products` (
  `orders_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `count_prod` INT NOT NULL DEFAULT '0',
  `price` DECIMAL(11,2) NOT NULL DEFAULT '0',
  INDEX `fk_order_products_orders1_idx` (`orders_id` ASC) VISIBLE,
  INDEX `fk_order_products_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_products_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `shop_cosmetics`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_products_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shop_cosmetics`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
